name: Keep Spam Classifier Streamlit App Awake

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Streamlit App
        run: |
          curl -I https://spammailclassifier8080.streamlit.app/
